baseURL = 'https://example.org/'
languageCode = 'de-de'
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = "true"
title = 'Meditation Bielefeld'
theme = 'hamburg'

[params]
	# Since 0.57.0 there's the concept of "main sections". The files for the section "posts" are in "./content/posts/".
	mainSections = ["posts"]

[languages]
    [languages.de]
        languageCode = "de"
        languageName = "Deutsch"
        copyright = "&copy; 2023 Meditation Bielefeld"

        [languages.de.params]
            subtitle = "\"Achtsamkeit ist eine Quelle des Glücks\""        
            
        [languages.de.menu]
            [[languages.de.menu.main]]
                name = "Veranstaltungen"
                identifier = "events"
                url = "pages/events"
            [[languages.de.menu.main]]
                name = "Thich Nhat Hanh"
                identifier = "thay"
                url = "pages/thay"
            [[languages.de.menu.main]]
                name = "Plum Village"
                identifier = "plumvillage"
                url = "pages/plumvillage"                
            [[languages.de.menu.main]]
                name = "EIAB"
                identifier = "eiab"
                url = "pages/eiab"
                

