baseURL = 'https://example.org/'
languageCode = 'de-de'
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = "true"
title = 'Meditation Bielefeld'
theme = 'hamburg'

[params]
	# Since 0.57.0 there's the concept of "main sections". The files for the section "posts" are in "./content/posts/".
	mainSections = ["pages"]
    nopagination = true
    copyright = "&copy; 2025 Meditation Bielefeld"
    subtitle = "\"Achtsamkeit ist eine Quelle des Glücks\""
    
[menu]
    [[menu.main]]
        name = "Veranstaltungen"
        identifier = "events"
        url = "pages/events"
        [[menu.main.params]]
            index = 0
    [[menu.main]]
        name = "Thich Nhat Hanh"
        identifier = "thay"
        url = "pages/thay"
        [[menu.main.params]]
            index = 1
    [[menu.main]]
        name = "Plum Village"
        identifier = "plumvillage"
        url = "pages/plumvillage"                
        [[menu.main.params]]
            index = 2
    [[menu.main]]
        name = "EIAB"
        identifier = "eiab"
        url = "pages/eiab"
        [[menu.main.params]]
            index = 3
    [[menu.main]]
        name = "Informationen"
        identifier = "info"
        url = "pages/info"
        [[menu.main.params]]
            index = 4